
#Aether: Lost Content World Configuration
["Animal Tweaks"]
	#
	# Allows Phygs and Flying Cows to spawn with Silver or Bronze wing colors.
	# This is a feature that was in the scrapped Mutation update for Aether II.
	# Default: true
	mutation_wing_colors = true
	#
	# Gives Phygs, Sheepuff, and Flying Cows unique sounds.
	# These are from the scrapped Mutation update for Aether II, although modified slightly.
	# Default: true
	mutation_animal_sounds = true

