version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      TYPE: AUTO_CURSEFORGE
      CF_API_KEY: $2a$10$3xFhQ7RkO19f6q3cUrJKpu41PW7mVsq5v0qbskRLvPImL4qTj/uvS
      CF_URL_PAGE: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5289491
      CF_SLUG: all-the-mods-9
      MEMORY: 4G
      DIFFICULITY: "normal"
      MAX_PLAYER: 10
      ENABLE_COMMAND_BLOCK: "true"
      MODE: "survival"
      ONLINE_MODE: "false"
      STOP_SERVER_ANNOUNCE_DELAY: 15
    volumes:
      - ../mc-data:/data
