version: "3.8"
networks:
  mc-docker:

services:
  mc:
    image: itzg/minecraft-server:java21
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    restart: unless-stopped
    healthcheck:
      test: mc-health
      start_period: 3m
      interval: 30s
      retries: 30
    environment:
      TZ: "Asia/Bangkok"
      EULA: "TRUE"
      TYPE: FORGE
      FORGE_VERSION: latest
      VERSION: 1.20.1
      MODPACK: "https://nextcloud.ofbas.com/s/mfXPH7CejJ367xq/download?path=%2F&files=mods.zip"
      REMOVE_OLD_MODS: "true"
      # CUSTOM_JAR_EXEC: "-jar arclight-forge-1.20.1-1.0.5.jar"
      # CF_API_KEY: $2a$10$3xFhQ7RkO19f6q3cUrJKpu41PW7mVsq5v0qbskRLvPImL4qTj/uvS
      # CF_URL_PAGE: https://www.curseforge.com/minecraft/modpacks/all-the-mods-9/files/5289491
      # CF_SLUG: all-the-mods-9
      # GENERIC_PACKS: mods
      # GENERIC_PACKS_PREFIX: https://nextcloud.ofbas.com/s/NytjPiX5SBj9iDK/download/
      # GENERIC_PACKS_SUFFIX: .zip
      MEMORY: 5G
      DIFFICULITY: "normal"
      MAX_PLAYER: 20
      ENABLE_COMMAND_BLOCK: "ture"
      MODE: "survival"
      ONLINE_MODE: "true"
      ALLOW_FLIGHT: "true"
      ENABLE_RCON: "true"
    volumes:
      - ../mc-data:/data
    networks: 
      - mc-docker
