name: Basu MC Server TESTER

on: [workflow_dispatch, push]

jobs:
  TestModsMC:
    name: MC Server mods test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Start server
      - name: Begin Build of BasuMC Docker Container 
        run: docker compose -f services/mc-server.yaml up --detach --wait # --wait-timeout 3000

      # Check Health
      - name: Get container health
        run: /usr/bin/docker container inspect -f "{{.State.Health.Status}}" services-mc-1
      - name: Display container logs
        run: /usr/bin/docker logs services-mc-1
