name: Basu MC Server TESTER

on: [workflow_dispatch, push]

jobs:
  TestModsMC:
    name: MC Server mods test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Start server
      - name: Begin Build of BasuMC Docker Container
        # continue-on-error: true
        # timeout-minutes: 4
        run: |
          docker compose -f services/mc-server.yaml up --exit-code-from mc &
          sleep 4m
          exit 0

      # Check Health
      # - name: Get container health
      #   run: |
      #     output=$(docker inspect -f "{{.State.Health.Status}}" services-mc-1)
      #     if [[ "$output" == "healthy" ]]; then
      #       echo "Exit code = 0" >> $GITHUB_OUTPUT
      #       exit 0
      #     else
      #       echo "Exit code = 1" >> $GITHUB_OUTPUT
      #       exit 1
      #     fi

