name: Basu MC Server Tester

on: [workflow_dispatch, push]

jobs:
  TestModsMC:
    name: MC Server mods test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Start server
      - name: Begin Build of BasuMC Docker Container
        run: docker compose -f services/mc-server.yaml up --wait # Start container and wait healthcheck
        id: startserver

      # Get Server log
      - name: Get Server Log
        if: always()
        run: docker logs services-mc-1
