name: Basu MC Server TESTER

on: [workflow_dispatch, push]

jobs:
  TestModsMC:
    name: MC Server mods test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Start server
      - name: Begin Build of BasuMC Docker Container
        continue-on-error: true
        timeout-minutes: 4
        run: docker compose -f services/mc-server.yaml up --exit-code-from services-mc-1

      # Sleep 3 Sec
      - run: sleep 3

      # Check Health
      - name: Get container health
        run: docker container inspect -f "{{.State.Health.Status}}" services-mc-1
