name: Basu MC Server Tester

on: [workflow_dispatch, push]

jobs:
  TestModsMC:
    name: MC Server mods test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: skip-workflow
        id: skip-workflow # id used for referencing step
        uses: saulmaldonado/skip-workflow@v1
        with:
          phrase: '[skip-workflow]'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # Start server
      - name: Begin Build of BasuMC Docker Container
        run: docker compose -f services/mc-server.yaml up --wait # Start container and wait healthcheck

      # Get log
      - name: Get server log
        run: docker logs services-mc-1
