name: Pipeline for testing

on: [push]

jobs:
  TestMC:
    name: MC Server running test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start server
        run: ./start.sh && sleep 5
      - name: Attach docker
        run: ./attach.sh
