name: Pipeline for testing

# on: [push]

jobs:
  TestModsMC:
    name: MC Server mods test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Start server
      - name: Start server
        run: ./start.sh
      - name: Starting server...
        run: sleep 3m

      # Check Health
      - name: Get container health
        run: /usr/bin/docker container inspect -f "{{.State.Health.Status}}" services-mc-1
      - name: Display container logs
        run: /usr/bin/docker logs services-mc-1
