name: Minecraft Server Mods 1.20.1
on: [push]
jobs:
  Begin-Server-Test:
    runs-on: ubuntu-latest
    steps:
      -name: Begin Minecraft Server mods test
      -run: chmod +x start-service && ./start-service
